services:
  kafka:
    image: apache/kafka:latest
    container_name: rag-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LOG_DIRS: /var/lib/kafka/data  
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - kafka-data:/var/lib/kafka/data 
    networks:
      - rag-net
    healthcheck:
        test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092 || exit 1"]
        interval: 10s
        timeout: 10s
        retries: 5
        start_period: 30s


  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: rag-kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_SERVLET_CONTEXTPATH: "/"
    depends_on:
      - kafka
    networks:
      - rag-net


  rag-chat-service:
    build:
      context: .
      dockerfile: backend/services/chat-service/Dockerfile
    container_name: rag-chat-service
    ports:
      - "8000:8000"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - DATABASE_URL=sqlite://///app/data/database.db
      - ENVIRONMENT=production
    volumes:
      - ./data:/app/data
      - ./data/uploaded_files:/app/uploads 
    depends_on:
      - kafka
    networks:
      - rag-net
    working_dir: /app


  rag-chat-worker:
    build:
      context: .
      dockerfile: backend/services/chat-service/Dockerfile-worker
    container_name: rag-chat-worker
    environment:
      - PYTHONPATH=/app:/app/src 
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - DATABASE_URL=sqlite://///app/data/database.db
      - ENVIRONMENT=production
    volumes:
      - ./data:/app/data
      - ./data/uploaded_files:/app/uploads 
    depends_on:
      - kafka
      - rag-chat-service
    networks:
      - rag-net
    working_dir: /app


  rag-llm-service:
      build:
        context: .
        dockerfile: backend/services/llm-service/Dockerfile
      container_name: rag-llm-service
      environment:
        - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
        - CONSUMER_GROUP=llm-worker-group
        - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
        - OLLAMA_MODEL=gemma3:12b
        - OLLAMA_BASE_URL=http://host.docker.internal:11434
        - OLLAMA_TEMPERATURE=0.3
        - MODEL_PATH=/app/models/snapshot/jina-embeddings-v3
        - HF_HUB_OFFLINE=1
        - HF_HUB_ENABLE_OFFLINE=1
        - TRANSFORMERS_OFFLINE=1
        - HF_HUB_DISABLE_SYMLINKS_WARNING=1
        - HF_HOME=/app/models/hf_cache
        - USE_HYDE=False
      volumes:
        - ./data/uploaded_files:/app/uploads 
        - ./models/snapshot/jina-embeddings-v3:/app/models/snapshot/jina-embeddings-v3
        - ./models/hf_cache:/app/models/hf_cache
        - ./models/faiss_index:/app/faiss_index
        - ./models/bm25_index:/app/bm25_index
        - ./models/BAAI/models--BAAI--bge-reranker-v2-m3:/app/models/BAAI/models--BAAI--bge-reranker-v2-m3
      depends_on:
        - kafka
      networks:
        - rag-net
      working_dir: /app
      

  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rag-react-app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://rag-chat-service:8000  
      - REACT_APP_WS_URL=ws://rag-chat-service:8000    
    depends_on:
      - rag-chat-service
    networks:
      - rag-net


networks:
  rag-net:
    driver: bridge


volumes:
  kafka-data:
  rag-chat-data:
  uploads-data:
  faiss-data: 